### ISSUE TITLE
Compile error with ESP32

### ISSUE THREAD

**Issue by FRT501** [natnqweb/SkyMap#4]
When using this line(in SkyMap.h), compiling for ESP32 
   SkyMap::SkyMap(ObserverPosition observer, CelestialObject *celestialobject, DateTimeValues datetime);
I get this error:
In file included from /media/entrepot/Arduinom/step_by_stepmod/step_by_stepmod.ino:1:
/media/entrepot/Arduinom/libraries/SkyMap/src/SkyMap.h:150:5: error: extra qualification 'SkyMap::' on member 'SkyMap' [-fpermissive]
  150 |     SkyMap::SkyMap(ObserverPosition observer, CelestialObject *celestialobject, DateTimeValues datetime);
      |     ^~~~~~
With this line , it works
SkyMap(ObserverPosition observer, CelestialObject *celestialobject, DateTimeValues datetime);

**Comment by natnqweb** [comment]
Thanks for information i will release patch(3.0.1) tomorrow with fixes. It seams like for some compilers there's a problem so i will remove this redundant qualification in next patch.

**Comment by natnqweb** [comment]
@FRT501 Thanks for support, fixes will be released in V3.0.1 and available in Arduino library manager or you can already clone master branch and use fixed library
